name: Bug Report
description: Create a bug report to help us improve metsymb
title: "[BUG]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there already an issue for this?
      description: Look at the [open](https://github.com/MeteoSwiss/metsymb/issues) and [closed](https://github.com/MeteoSwiss/metsymb/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+) issues.
      options:
        - label: I found no existing ticket for this bug.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Tell us what happened and (if applicable) what you expected.
      placeholder: Describe the bug
      value: "A clear and concise description of what happened."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Python**: 3.11.1
          - **metsymb**: 1.2.0
      value: |
          - OS:
          - Python:
          - dvas:
      render: markdown
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MeteoSwiss/metsymb/blob/develop/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the metsymb Code of Conduct.
          required: true
